ISSBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: ISSBlogBundle:Post:index }
    requirements:
        _method:  GET

ISSBlogBundle_view:
    pattern: /view/{id}
    defaults: { _controller: ISSBlogBundle:Post:view }
    requirements:
        _method:  GET
        id: \d+

_facebook_secured:
      pattern: /secured/
      defaults: { _controller: ISSBlogBundle:Post:index }

_security_check:
    pattern:  /login_check

_security_logout:
    pattern:  /logout

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

_facebook_secured:
    pattern: /secured/
    defaults: { _controller: ISSBlogBundle:Post:index }