parameters:
    vkAppId: 4197935
    vkSecret: 1oKQTncWkEmzdUENshmU
    vkApiUrl: api.vk.com/api.php

services:
    VkApiService:
        class: ISS\BlogBundle\Service\VkApiService
        arguments: [%vkAppId%, %vkSecret%, %vkApiUrl%]

