parameters:
#    iss_blog.example.class: ISS\BlogBundle\Example

services:
#    iss_blog.example:
#        class: %iss_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
