parameters:
    vkAppId: 4197935
    vkSecret: 1oKQTncWkEmzdUENshmU
    vkApiUrl: https://api.vk.com/

services:
    VkApiService:
        class: ISS\BlogBundle\Service\VkApiService
        arguments: [%vkAppId%, %vkSecret%, %vkApiUrl%]

