parameters:
    facebook.appId: 669439826427579
    facebook.secret: 658d62dcc3e7fae75a7808625ea52ff0

services:
    facebook:
        class: ISS\BlogBundle\Service\Facebook
        arguments: [{ appId: %facebook.appId%, secret: %facebook.secret% }]
