parameters:
#    iss_site.example.class: ISS\SiteBundle\Example

services:
#    iss_site.example:
#        class: %iss_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
